# Generated by Django 4.2.6 on 2023-10-15 13:07

from django.db import migrations, models
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_remove_studentdata_image_url_studentdata_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='image_urls',
            field=models.JSONField(default={'urls': []}, verbose_name=model.models.f3),
            preserve_default=False,
        ),
    ]
