# Generated by Django 4.2.6 on 2023-10-15 13:08

from django.db import migrations, models
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_studentdata_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='image_urls',
            field=models.JSONField(default=model.models.f3),
        ),
    ]
