# Generated by Django 4.2.6 on 2023-10-22 20:30

from django.db import migrations, models
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_studentdata_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='join_password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='join_token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='institute',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.JSONField(default=model.models.f2, null=True),
        ),
    ]
